#!/usr/bin/bash


toggle() {
  STATUS="$(bluetoothctl show | grep Powered | awk '{print $2}')"
  if [ $STATUS == "yes" ]; then
    bluetoothctl power off
  else
    bluetoothctl power on
  fi
}

icon() {
  # not connected
  if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
    echo "󰂲"
  else
    #on
    if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]; then
      echo "󰂯"
    else
      echo "󰂱"
    fi
  fi
}

class() {
  # off
  if [ $(bluetoothctl show | grep "Powered: yes" | wc -c) -eq 0 ]; then
    echo "off"
  else
    # on
    if [ $(echo info | bluetoothctl | grep 'Device' | wc -c) -eq 0 ]; then
      echo "on"
    else
      echo "connected"
    fi
  fi
}

if [[ $1 == "--toggle" ]]; then
  toggle
elif [[ $1 == "--icon" ]]; then
  icon
elif [[ $1 == "--class" ]]; then
  class
fi

