theme = "catppuccin_mocha"

[editor]
bufferline = "multiple"
color-modes = true

[editor.statusline]
left = ["mode", "spinner", "file-name"]
center = []
right = ["file-type", "diagnostics", "selections", "position", "total-line-numbers", "file-encoding"]
mode.normal = "NORMAL"
mode.insert = "INSERT"
mode.select = "SELECT"

[editor.cursor-shape]
normal = "block"
insert = "bar"
select = "block"

[editor.lsp]
display-signature-help-docs = false
